# Generated by Django 5.1.3 on 2024-11-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseprogress_delete_studentprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(),
        ),
    ]
